export const productData = [
  {
    id: 1,
    name: "HEAVY DUTY SHREDDER",
    slug: "heavy-duty-shredder",
    category: "Industrial Shredders",
    model: "HD-3000X",
    image: "/assets/images/product one.png",
    highlights: [
      "Advanced shredding technology",
      "High throughput capacity",
      "Robust construction",
      "Energy efficient operation",
    ],
    description:
      "Industrial-grade shredder designed for efficient biomass waste processing with superior durability and performance.",
    specifications: {
      capacity: "3000 kg/hr",
      power: "75 kW",
      dimensions: "3200 x 1800 x 2400 mm",
      weight: "5200 kg",
      cutting_chamber: "1500 x 1200 mm",
      rotor_speed: "85 rpm",
      screen_size: "50-100 mm adjustable",
    },
    features: [
      "Hydraulic power transmission",
      "Automatic reverse function on overload",
      "Hardened steel cutting tools",
      "Touch screen control panel",
      "Remote monitoring capability",
      "Integrated cooling system",
    ],
    applications: [
      "Wood waste processing",
      "Biomass preparation",
      "Recycling plants",
      "Agricultural waste",
    ],
    maintenance_interval: "500 operating hours",
    warranty: "2 years standard warranty",
  },
  {
    id: 2,
    name: "HEAVY DUTY SECONDARY SHREDDER",
    slug: "heavy-duty-secondary-shredder",
    category: "Secondary Processing",
    model: "SS-2000",
    image: "/assets/images/product two.jpg",
    highlights: [
      "Fine particle size control",
      "Consistent output quality",
      "Low maintenance design",
      "Automated operation",
    ],
    description:
      "Secondary processing unit for achieving precise particle sizes in biomass material preparation.",
    specifications: {
      capacity: "2000 kg/hr",
      power: "55 kW",
      dimensions: "2800 x 1600 x 2200 mm",
      weight: "4200 kg",
      cutting_chamber: "1200 x 1000 mm",
      rotor_speed: "120 rpm",
      screen_size: "10-50 mm adjustable",
    },
    features: [
      "Precision cutting system",
      "Variable speed drive",
      "Self-sharpening cutters",
      "Automatic feed control",
      "Dust collection system",
      "Energy optimization system",
    ],
    applications: [
      "Fine material processing",
      "Pellet preparation",
      "Size reduction",
      "Uniform particle production",
    ],
    maintenance_interval: "400 operating hours",
    warranty: "2 years standard warranty",
  },
  {
    id: 3,
    name: "DEWATERING PRESS UNIT",
    slug: "dewatering-press-unit",
    category: "Moisture Control",
    model: "DPU-1500",
    image: "/assets/images/three.jpg",
    highlights: [
      "High moisture removal efficiency",
      "Continuous operation capability",
      "Adjustable pressure control",
      "Integrated filtration system",
    ],
    description:
      "Advanced dewatering system for efficient moisture reduction in biomass materials.",
    specifications: {
      capacity: "1500 kg/hr",
      power: "45 kW",
      dimensions: "2500 x 1400 x 2000 mm",
      weight: "3800 kg",
      pressure: "Up to 300 bar",
      moisture_reduction: "Up to 60%",
      filtration: "Self-cleaning system",
    },
    features: [
      "Progressive cavity pump",
      "Automatic pressure regulation",
      "Stainless steel construction",
      "Digital moisture monitoring",
      "Continuous discharge system",
      "Advanced filtrate handling",
    ],
    applications: [
      "Organic waste dewatering",
      "Sludge processing",
      "Biomass preparation",
      "Industrial waste treatment",
    ],
    maintenance_interval: "300 operating hours",
    warranty: "2 years standard warranty",
  },
  {
    id: 4,
    name: "THERMO DRYER",
     slug: "thermo-dryer",
    category: "Thermal Processing",
    model: "TD-2500",
    image: "/assets/images/four.jpg",
    highlights: [
      "Precise temperature control",
      "Energy-efficient design",
      "Multiple drying zones",
      "Automatic moisture monitoring",
    ],
    description:
      "State-of-the-art thermal drying solution for optimal moisture content in processed biomass.",
    specifications: {
      capacity: "2500 kg/hr",
      power: "90 kW",
      dimensions: "4000 x 2000 x 2500 mm",
      weight: "6500 kg",
      temperature_range: "30-150°C",
      heating_zones: "3 independent zones",
      moisture_reduction: "Up to 80%",
    },
    features: [
      "Multi-zone temperature control",
      "Heat recovery system",
      "Automatic moisture sensing",
      "Variable speed conveyor",
      "PLC control system",
      "Emergency cooling system",
    ],
    applications: [
      "Biomass drying",
      "Agricultural products",
      "Wood processing",
      "Industrial materials",
    ],
    maintenance_interval: "450 operating hours",
    warranty: "2 years standard warranty",
  },
  {
    id: 5,
    name: "BIO COMPACTOR",
     slug: "bio-compactor",
    category: "Densification",
    model: "BC-1000",
    image: "/assets/images/five.png",
    highlights: [
      "High compression ratio",
      "Uniform density output",
      "Easy maintenance access",
      "Advanced control system",
    ],
    description:
      "Advanced biomass compaction system for producing high-quality fuel briquettes.",
    specifications: {
      capacity: "1000 kg/hr",
      power: "60 kW",
      dimensions: "2800 x 1500 x 2200 mm",
      weight: "4800 kg",
      compression_ratio: "1:8",
      briquette_size: "90 mm diameter",
      density: "1.2 g/cm³",
    },
    features: [
      "Hydraulic compression system",
      "Automatic density control",
      "Quick-change die system",
      "Temperature monitoring",
      "Overload protection",
      "Production data logging",
    ],
    applications: [
      "Biomass briquetting",
      "Fuel production",
      "Waste volume reduction",
      "Material densification",
    ],
    maintenance_interval: "350 operating hours",
    warranty: "2 years standard warranty",
  },
];
